Repository ERICA-SW-TEAM-project-5th/Invaders, pull requests merged in 2020-12, with the labels that each got.

#8 SP1-13 / issue #7 resolved
  scores
  src/engine/DrawManager.java
  src/engine/FileManager.java
  src/graphics
  src/scores
  src/screen/HighScoreScreen.java
  src/screen/TitleScreen.java
Labels: enhancement

#12 SP1-13 Feature/score reset 완료
  scores
  src/engine/DrawManager.java
  src/engine/FileManager.java
  src/graphics
  src/scores
  src/screen/HighScoreScreen.java
  src/screen/TitleScreen.java
Labels: finished

#11 SP1-14 게임 실행 오류 해결
  src/graphics
  src/scores
Labels: bug

#15 SP1-14 Hotfix to master
  src/graphics
  src/scores
Labels: Hotfix

#16 SP1-14 Hotfix to develop
  res/graphics
  res/scores
Labels: Hotfix

#10 SP1-12 / issue #6 resolved
  src/screen/GameScreen.java
Labels: enhancement

#19 SP1-17 Merge Feature/convert maven
  .gitignore
  pom.xml
  src/engine/CoreTest.java
  target/classes/META-INF/MANIFEST.MF
  target/classes/META-INF/maven/Invaders/Invaders/pom.properties
  target/classes/META-INF/maven/Invaders/Invaders/pom.xml
  target/classes/engine/Cooldown.class
  target/classes/engine/Core.class
  target/classes/engine/CoreTest.class
  target/classes/engine/DrawManager$SpriteType.class
  target/classes/engine/DrawManager.class
  target/classes/engine/FileManager.class
  target/classes/engine/Frame.class
  target/classes/engine/GameSettings.class
  target/classes/engine/GameState.class
  target/classes/engine/InputManager.class
  target/classes/engine/MinimalFormatter.class
  target/classes/engine/Score.class
  target/classes/entity/Bullet.class
  target/classes/entity/BulletPool.class
  target/classes/entity/EnemyShip.class
  target/classes/entity/EnemyShipFormation$Direction.class
  target/classes/entity/EnemyShipFormation.class
  target/classes/entity/Entity.class
  target/classes/entity/Ship.class
  target/classes/graphics
  target/classes/scores
  target/classes/screen/GameScreen.class
  target/classes/screen/HighScoreScreen.class
  target/classes/screen/ScoreScreen.class
  target/classes/screen/Screen.class
  target/classes/screen/TitleScreen.class
  target/scores
Labels: finished

#20 SP1-12 Merge Feature/pause
  src/screen/GameScreen.java
Labels: finished

#21 SP1-18 Release ver. 1.0
  .gitignore
  pom.xml
  scores
  src/engine/CoreTest.java
  src/engine/DrawManager.java
  src/engine/FileManager.java
  src/screen/GameScreen.java
  src/screen/HighScoreScreen.java
  src/screen/TitleScreen.java
  target/classes/META-INF/MANIFEST.MF
  target/classes/META-INF/maven/Invaders/Invaders/pom.properties
  target/classes/META-INF/maven/Invaders/Invaders/pom.xml
  target/classes/engine/Cooldown.class
  target/classes/engine/Core.class
  target/classes/engine/CoreTest.class
  target/classes/engine/DrawManager$SpriteType.class
  target/classes/engine/DrawManager.class
  target/classes/engine/FileManager.class
  target/classes/engine/Frame.class
  target/classes/engine/GameSettings.class
  target/classes/engine/GameState.class
  target/classes/engine/InputManager.class
  target/classes/engine/MinimalFormatter.class
  target/classes/engine/Score.class
  target/classes/entity/Bullet.class
  target/classes/entity/BulletPool.class
  target/classes/entity/EnemyShip.class
  target/classes/entity/EnemyShipFormation$Direction.class
  target/classes/entity/EnemyShipFormation.class
  target/classes/entity/Entity.class
  target/classes/entity/Ship.class
  target/classes/graphics
  target/classes/scores
  target/classes/screen/GameScreen.class
  target/classes/screen/HighScoreScreen.class
  target/classes/screen/ScoreScreen.class
  target/classes/screen/Screen.class
  target/classes/screen/TitleScreen.class
  target/scores
Labels: finished, release

#22 SP1-17 Fixed .gitignore
  .gitignore
  target/classes/META-INF/MANIFEST.MF
  target/classes/META-INF/maven/Invaders/Invaders/pom.properties
  target/classes/META-INF/maven/Invaders/Invaders/pom.xml
  target/classes/engine/Cooldown.class
  target/classes/engine/Core.class
  target/classes/engine/CoreTest.class
  target/classes/engine/DrawManager$SpriteType.class
  target/classes/engine/DrawManager.class
  target/classes/engine/FileManager.class
  target/classes/engine/Frame.class
  target/classes/engine/GameSettings.class
  target/classes/engine/GameState.class
  target/classes/engine/InputManager.class
  target/classes/engine/MinimalFormatter.class
  target/classes/engine/Score.class
  target/classes/entity/Bullet.class
  target/classes/entity/BulletPool.class
  target/classes/entity/EnemyShip.class
  target/classes/entity/EnemyShipFormation$Direction.class
  target/classes/entity/EnemyShipFormation.class
  target/classes/entity/Entity.class
  target/classes/entity/Ship.class
  target/classes/graphics
  target/classes/scores
  target/classes/screen/GameScreen.class
  target/classes/screen/HighScoreScreen.class
  target/classes/screen/ScoreScreen.class
  target/classes/screen/Screen.class
  target/classes/screen/TitleScreen.class
  target/scores
Labels: enhancement

#23 SP1-17 Merge Feature/convert maven 2
  .gitignore
  target/classes/META-INF/MANIFEST.MF
  target/classes/META-INF/maven/Invaders/Invaders/pom.properties
  target/classes/META-INF/maven/Invaders/Invaders/pom.xml
  target/classes/engine/Cooldown.class
  target/classes/engine/Core.class
  target/classes/engine/CoreTest.class
  target/classes/engine/DrawManager$SpriteType.class
  target/classes/engine/DrawManager.class
  target/classes/engine/FileManager.class
  target/classes/engine/Frame.class
  target/classes/engine/GameSettings.class
  target/classes/engine/GameState.class
  target/classes/engine/InputManager.class
  target/classes/engine/MinimalFormatter.class
  target/classes/engine/Score.class
  target/classes/entity/Bullet.class
  target/classes/entity/BulletPool.class
  target/classes/entity/EnemyShip.class
  target/classes/entity/EnemyShipFormation$Direction.class
  target/classes/entity/EnemyShipFormation.class
  target/classes/entity/Entity.class
  target/classes/entity/Ship.class
  target/classes/graphics
  target/classes/scores
  target/classes/screen/GameScreen.class
  target/classes/screen/HighScoreScreen.class
  target/classes/screen/ScoreScreen.class
  target/classes/screen/Screen.class
  target/classes/screen/TitleScreen.class
  target/scores
Labels: finished

#25 SP1-10 Feature/difficulty done
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/InputManager.java
  src/entity/Bullet.java
  src/entity/EnemyShipFormation.java
  src/entity/Entity.java
  src/screen/DifficultyScreen.java
  src/screen/GameScreen.java
  src/screen/Screen.java
Labels: finished

#27 SP1-7 / issue #1
  .gitignore
  src/engine/Core.java
  src/engine/DrawManager.java
  src/engine/GameState.java
  src/entity/Bullet.java
  src/entity/Ship.java
  src/font.ttf
  src/screen/GameScreen.java
Labels: enhancement
